import type { Blueprint, DatabaseMode } from "./types.js";

const defaultBlueprint: Blueprint = {
  projectName: "Stacksmith Project",
  summary: "A local-first app generated by Stacksmith.",
  targetUsers: ["Builders"],
  screens: ["Home/workspace"],
  components: ["App shell", "Primary content area"],
  dataModels: ["No data model required yet"],
  apiRoutes: ["GET /api/health"],
  auth: "Not included in this version",
  databaseMode: "none",
  envVars: [],
  fileStructure: ["package.json", "src/App.tsx", "server/index.ts", "shared/types.ts"],
  integrations: [],
  risks: ["Requirements may need refinement before production use"],
  unclearRequirements: ["Deployment target is not selected"],
  buildSteps: ["npm install", "npm run dev"],
  generatedStack: ["React", "Vite", "TypeScript", "Node API"],
  notGeneratedYet: ["Production hosting", "Authentication", "Supabase integration", "Mobile app generation"],
};

export function normalizeBlueprint(input: unknown): Blueprint {
  const record = isRecord(input) ? input : {};
  const databaseMode = readDatabaseMode(record.databaseMode);
  const projectName = readString(record.projectName, defaultBlueprint.projectName);

  return {
    projectName,
    summary: readString(record.summary, defaultBlueprint.summary),
    targetUsers: readStringArray(record.targetUsers, defaultBlueprint.targetUsers),
    screens: readStringArray(record.screens, defaultBlueprint.screens),
    components: readStringArray(record.components, defaultBlueprint.components),
    dataModels: readStringArray(
      record.dataModels ?? record.dataModel,
      databaseMode === "sqlite" ? ["SQLite-ready local data model"] : defaultBlueprint.dataModels,
    ),
    apiRoutes: readStringArray(record.apiRoutes, defaultBlueprint.apiRoutes),
    auth: readString(record.auth, defaultBlueprint.auth),
    databaseMode,
    envVars: readStringArray(record.envVars, defaultBlueprint.envVars),
    fileStructure: readStringArray(record.fileStructure, defaultBlueprint.fileStructure),
    integrations: readStringArray(record.integrations, defaultBlueprint.integrations),
    risks: readStringArray(record.risks, defaultBlueprint.risks),
    unclearRequirements: readStringArray(record.unclearRequirements, defaultBlueprint.unclearRequirements),
    buildSteps: readStringArray(record.buildSteps, defaultBlueprint.buildSteps),
    generatedStack: readStringArray(record.generatedStack, defaultBlueprint.generatedStack),
    notGeneratedYet: readStringArray(record.notGeneratedYet, defaultBlueprint.notGeneratedYet),
  };
}

export function buildBlueprintPrompt(input: {
  prompt: string;
  databaseMode: DatabaseMode;
}): string {
  return `You are Stacksmith, a local-first AI app studio. Create a concise JSON blueprint only.

Return valid JSON with these keys:
projectName, summary, targetUsers, screens, components, dataModels, apiRoutes, auth, databaseMode, envVars, fileStructure, integrations, risks, unclearRequirements, buildSteps, generatedStack, notGeneratedYet.

Rules:
- databaseMode must be "${input.databaseMode}".
- The generated stack is React, Vite, TypeScript, a small Node API, and optional SQLite-ready structure.
- Do not include production hosting, Supabase implementation, mobile apps, or real authentication as generated features.
- Be honest about unclear requirements.

User app idea:
${input.prompt}`;
}

function readDatabaseMode(value: unknown): DatabaseMode {
  return value === "sqlite" ? "sqlite" : "none";
}

function readString(value: unknown, fallback: string): string {
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}

function readStringArray(value: unknown, fallback: string[]): string[] {
  if (Array.isArray(value)) {
    const strings = value.filter((item): item is string => typeof item === "string").map((item) => item.trim()).filter(Boolean);
    return strings.length ? strings : fallback;
  }

  if (typeof value === "string" && value.trim()) {
    return [value.trim()];
  }

  return fallback;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
